### ISSUE TITLE
[Bug]: When using forge build, forge test, result is always the same and weirdly not compiling the changes

### ISSUE THREAD

**Issue by MiguelBits** [smartcontractkit/foundry-starter-kit-old#17]
### Describe the bug

This is my function, the compiler should throw error at it, as it previously was :   
![image](https://user-images.githubusercontent.com/15989933/167674301-61492d24-d956-4b1a-8da5-e1c7456e5c2b.png)
This is the output of forge test :  
![image](https://user-images.githubusercontent.com/15989933/167674382-3dff75e6-8230-4a06-be10-d7d0d78265d1.png)
When I run forge test -vvvvv result is the same as the image above, previously it was not! I have a couple of tests written that were working before.

### To Reproduce

1. write any code
2. forge test
3. does not compile properly

### Expected behavior

Compiling and showing error traces

### Additional context

Already did cargo update on the foundry folder

**Comment by mattsse** [comment]
this could be windows paths related

could you please share the verbose output of the commands prefixed with `RUST_LOG=ethers=trace`

like `RUST_LOG=ethers=trace forge test`

also, just noticed, this not actually this repo, any chance for me to reproduce this issue?
what's your `forge config` and workspace look like?

**Comment by MiguelBits** [comment]
my forge config ```
[default]
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
bytecode_hash = 'ipfs'
cache = true
cache_path = 'cache'
evm_version = 'london'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 256
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = ['lib']
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
optimizer = true
optimizer_runs = 200
out = 'out'
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib\forge-std\lib\ds-test\src/',
    'forge-std/=lib\forge-std\src/',
    'openzeppelin-contracts/=lib\openzeppelin-contracts/',
]
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
sizes = false
sparse_mode = false
src = 'src'
test = 'test'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
verbosity = 0
via_ir = false

[default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'
```

**Comment by MiguelBits** [comment]
I fixed this issue, by using Ubuntu instead of Windows, lol
