### ISSUE TITLE
[Enhancement]: Todo #2 Network and Contract Choice

### ISSUE THREAD

**Issue by shankars99** [smartcontractkit/foundry-starter-kit-old#18]
### What would you like us to improve?

I could work on the 2nd Todo list topic (Network and Contract Choice)

Just wanted to know how to go about it. 

For networks could I do something like flags so 

```deploy.sh --network ropsten```
would work where in the switch case it maps ropsten to http://xxx.ropsten.yyy

For contracts i guess something like iterate through the folder `src/` and offer all `*.sol` as options.

I'm not really sure if this is where/how i should ask these questions, if needed I could change it.

### How important it is?

Not very, quality of life improvement

**Comment by PatrickAlphaC** [comment]
This for this issue! 

Actually, the Foundry team is working on a deploy built-in functionality - so I think we should hold off till that's done.

**Comment by shankars99** [comment]
Oh wow, that's great then. 
Yeah we could hold off until that's done, in the meantime I'll look into some other issues or things in the Todo list that I could tackle.

Thanks for the foundry-starter-kit repository though, loving it
