### ISSUE TITLE
Make install step fails 

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/foundry-starter-kit-old#5]
Hello

I ran into 2 issues when running `make`

1.  1st issue

```
Error:
   0: "/xxx/foundry-starter-kit/lib/chainlink-brownie-contracts/src/v0.8/ChainlinkClient.sol": No such file or directory (os error 2)
```

Which can be solved by completing the _install_ step in _Makefile_ . It Shoud be:

`install :; forge install dapphub/ds-test && forge install rari-capital/solmate && forge install brockelmore/forge-std && forge install ZeframLou/clones-with-immutable-args && forge install smartcontractkit/chainlink-brownie-contracts`

1. 2nd issue: Also, the `dappbuild` step failed with this error

```
ParserError: Source "ds-test/test.sol" not found: File not found.
 --> src/test/APIConsumer.t.sol:7:1:
  |
7 | import "ds-test/test.sol";
```
A remapping has to be added to the _remappings.txt_ file

**Comment by PatrickAlphaC** [comment]
Thank you!!
