### ISSUE TITLE
dependency install failed

### ISSUE THREAD

**Issue by 7flash** [smartcontractkit/foundry-starter-kit-old#9]
![image](https://user-images.githubusercontent.com/4569866/160654249-c69f669e-e0e4-4726-8eea-b566992e9926.png)

https://github.com/smartcontractkit/chainlink-brownie-contract

The above repository does not exist

Maybe should be replaced with smartcontractkit/chainlink-mix ?

**Comment by 7flash** [comment]
Found the correct repository: 

[smartcontractkit/chainlink-brownie-contracts](https://github.com/smartcontractkit/chainlink-brownie-contracts)

**Comment by 7flash** [comment]
Please merge https://github.com/smartcontractkit/foundry-starter-kit/pull/10 @PatrickAlphaC

**Comment by PatrickAlphaC** [comment]
Ah!! Thank you!!
